### ISSUE TITLE
Akka and licencing

### ISSUE THREAD

**Issue by nicl** [guardian/scala-steward-public-repos#53]
Hey all, Akka have changed their licencing and, without deliberate action, Scala Steward will happily update to a commercial version :(. Snyk's licence checking is currently not working for Akka (we have raised this with them) so that is not yet a solution.

The proposal is therefore to ignore updates for  groupId `com.typesafe.akka` and `com.lightbend.akka` by adding the following:

```
updates.ignore = [ { groupId = "com.typesafe.akka" }, {groupId = "com.lightbend.akka"} ]
```

This will mean that we don't automatically get security updates for Akka (but Snyk should still flag issues). But does mean we won't sleepwalk into a load of licence violations until we have a better solution here.

To clarify, this should be considered a **temporary** solution until we have a better approach to Akka replacement going forward.

To illustrate the problem, here is a PR that accidentally does this and which we'll need to revert:

* https://github.com/guardian/discussion-avatar/pull/85

cc @rtyley and @akash1810 for thoughts on this.

**Comment by kelvin-chappell** [comment]
Perhaps add a job to the existing security workflows to inspect the `dependencyList` and fail if it includes undesirable dependencies.

**Comment by akash1810** [comment]
Summarising our IRL discussion: Not all of our repositories are configured to use Scala Steward, so a solution here wouldn't be exhaustive. An alternative might be to create a GitHub Action, and add it to any Scala-like repository, running at PR time? 

The [nori](https://github.com/Financial-Times/nori) tool could be used to roll it out, or we could make it a [mandatory workflow](https://docs.github.com/en/actions/using-workflows/required-workflows).

**Comment by rtyley** [comment]
> Not all of our repositories are configured to use Scala Steward, so a solution here wouldn't be exhaustive.

Yup - though updating our global [scala-steward.conf](https://github.com/guardian/scala-steward-public-repos/blob/main/scala-steward.conf) with the `updates.ignore` is definitely still worth doing, to prevent Scala Steward from trying to do the wrong thing!


> An alternative might be to create a GitHub Action, and add it to any Scala-like repository, running at PR time?

Just a note that we could maybe reuse something from the Scala Steward apps here, and define 'Scala-like repository' as being any repo that the '[gu-scala-steward-public-repos](https://github.com/apps/gu-scala-steward-public-repos)' or '[gu-scala-steward-private-repos](https://github.com/apps/gu-scala-steward-private-repos)' GitHub apps have access to (as Scala Steward now does, see https://github.com/guardian/scala-steward-public-repos/pull/46).

> https://github.com/hmrc/sbt-bobby might also offer a solution here.

Oh, interesting find!

**Comment by nicl** [comment]
(Closing as this is now merged.)
